### ISSUE TITLE
What's the license?

### ISSUE THREAD

**Issue by turion** [effectfully/Generic#3]
I'd like to add this library to nixpkgs/NixOS. What is its license? Is it even open source?

**Comment by effectfully** [comment]
Thank you!

Just licensed the library using the MIT license.

As of now the library probably does not build with a recent version of Agda. I'll make it up-to-date as soon as I can.

**Comment by effectfully** [comment]
Updated the library to Agda 2.6.1.

**Comment by effectfully** [comment]
... and released version 0.1.
